name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Build Docker image
      uses: docker/build-push-action@master
      with:
        context: .
        push: false
        tags: robot:latest robot:$(date +%s)

    - name: Run Docker container
      uses: docker/metadata-action@master
      with:
        images: robot:latest
        entrypoint: python3.11 -m robot.run --version