name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag robot:$(date +%s) --tag robot:latest
    - name: Test and Print Version
      run: docker run robot:latest --version