name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


env:
  IMAGE_NAME: robot

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Build Docker image
      uses: docker/build-push-action@master
      with:
        context: .
        push: false
        tags: ${{ env.IMAGE_NAME }}:latest

    - name: Run Docker Execute Self Test
      run: |
          docker run --rm \
          -e MY_ENV_VAR=my_value \
          ${{ env.IMAGE_NAME }}:latest \
          .
